FROM node:6
WORKDIR /usr/src/app

# dumb-init
RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.1.3/dumb-init_1.1.3_amd64
RUN chmod +x /usr/local/bin/dumb-init

COPY package.json /usr/src/app/package.json
RUN npm install

COPY . /usr/src/app
RUN npm run build
RUN rm -rf /usr/src/app/node_modules && npm install --production

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]
CMD ["npm", "run", "start-production"]
