FROM openjdk:8-jdk
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
EXPOSE 8080

# dumb-init
RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.1.3/dumb-init_1.1.3_amd64 && chmod +x /usr/local/bin/dumb-init

COPY . /usr/src/app

ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]
CMD ["./gradlew", "bootRun"]
